import random
import requests
import json

from copyleaks.copyleaks import Copyleaks
from copyleaks.exceptions.command_error import CommandError


# Copyleaks Account credintials 
EMAIL_ADDRESS= 'hassan.n.afif@gmail.com'
KEY = '8931adbf-b8ee-4868-b694-3e01dce8c9b8'

# Authenticating Process
try:
    auth_token = Copyleaks.login(EMAIL_ADDRESS, KEY)    
except CommandError as ce:
    response = ce.get_response()
    print(f"An error occurred (HTTP status code {response.status_code}):")
    print(response.content)
    exit(1)



# Submeting and exporting needed data
scan_id = random.randint(100, 100000)

headers = {
    'Content-type': 'application/json',
    'Authorization': f"Bearer {auth_token['access_token']}"
}


# Sending the file for AI-detection scan and retrieve response data

# Use the folowing function to check for AI generated text

def ai_detection(text: str):
    try: 
        scan_file = json.dumps({'text':text})
        response = requests.post('https://api.copyleaks.com/v2/writer-detector/{scan_id}/check', headers=headers, data=scan_file)
        txt = response.content
        txt = json.loads(txt)
        results = txt['results']
        isAi = True if results[0]['classification'] == 2 else False
        probapility = str(round(results[0]['probability'] * 100)) + '%'
        msg = "Generated By AI" if isAi else "Free of AI generated content"
        res = dict({'Msg':msg,'Confidence probability':probapility,'isAI':isAi})
        return res
    except KeyError:
        print('Your text is very short')
    



if __name__ == "__main__":
    print(ai_detection("Some costs are incurred only when inflation is unanticipated, while other costs arise even when the inflation is fully anticipated. When unanticipated, price signals can become misinterpreted,and this can reduce economic efficiency. But once individuals adjust to the new higher inflation rate, accurate price signals are restored, and so this cost is only temporary. Only one-time increases in inflation are typically unexpected.Periods of sustained increasing inflation are typically anticipated because when prices rise in one month,individuals and markets may likely anticipate prices to rise in the following month. "))

